<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AzureFunctionsVersion>v4</AzureFunctionsVersion>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Azure.Storage.Blobs" Version="12.25.0" />
    <PackageReference Include="ClosedXML" Version="0.105.0" />
    <PackageReference Include="HttpMultipartParser" Version="9.0.0" />
    <PackageReference Include="Microsoft.ApplicationInsights.WorkerService" Version="2.23.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="2.0.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.ApplicationInsights" Version="2.0.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore" Version="2.0.1" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="2.0.2" />
    <PackageReference Include="NPOI" Version="2.7.4" />
    <PackageReference Include="YamlDotNet" Version="16.3.0" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Templates\" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="Templates\data_output.json" />
    <Content Include="Templates\data_output.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <None Remove="Templates\ExcelMappingInput.yaml" />
    <Content Include="Templates\ExcelMappingInput.yaml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <None Remove="Templates\ExcelMappingInputLogistic.yaml" />
    <Content Include="Templates\ExcelMappingInputLogistic.yaml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <None Remove="Templates\ExcelMappingOutput.yaml" />
    <Content Include="Templates\ExcelMappingOutput.yaml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <None Remove="Templates\ExcelMappingOutputLogistic.yml" />
    <Content Include="Templates\ExcelMappingOutputLogistic.yml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <None Remove="Templates\ExcelSapMappingInput.yml" />
    <Content Include="Templates\ExcelSapMappingInput.yml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <None Remove="Templates\template_sap_output.xlsx" />
    <Content Include="Templates\template_sap_output.xlsx">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <None Remove="Templates\template_output_logistica.xlsx" />
    <Content Include="Templates\template_output_logistica.xlsx">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <None Remove="Templates\template_output.xlsx" />
    <Content Include="Templates\template_output.xlsx">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>